name: Build project
run-name: ${{ github.actor }} is building the project.
on: [workflow_dispatch]
jobs:
    Build-robot-source:
        runs-on: ubuntu-22.04
        steps:
            - name: Checkout
              uses: actions/checkout@v4
              with:
                submodules: true
            - name: Git Submodule Update
              run: |
                git submodule update
            - run: sudo apt-get update
            - run: sudo apt-get -y install gcc-aarch64-linux-gnu
            - run: sudo apt-get -y install g++-aarch64-linux-gnu
            - run: sudo apt-get -y install cmake
            - run: git -C ${{ github.workspace }} submodule update
            - uses: actions/checkout@v4
            - run: mkdir -p ${{ github.workspace }}/build
            - name: Configure CMake
              run: cmake -DCMAKE_TOOLCHAIN_FILE=../robot-src/Toolchain-RaspberryPi.cmake robot-src -B ${{ github.workspace }}/build
            - run: cmake --build ${{ github.workspace }}/build
            - name: Upload artifact
              uses: actions/upload-artifact@v4
              with:
                name: robot-server
                path: ${{ github.workspace }}/build/robot-server